### ISSUE TITLE
publish package to NPM

### ISSUE THREAD

**Issue by knksmith57** [lawnsea/generator-eslintrc#2]
Looks like this hasn't been published yet? --> https://www.npmjs.com/package/generator-eslintrc

```
❱ npm search generator-eslintrc
No match found for "generator-eslintrc"
```

**Comment by knksmith57** [comment]
In the meantime, people can get away with installing using a github ref:

```
❱ npm install -g generator-eslintrc@lawnsea/generator-eslintrc
```

**Comment by lawnsea** [comment]
Turns out I did this, apparently...
